// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naezyfrpxgpnegqwiqan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZXp5ZnJweGdwbmVncXdpcWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjU5NzAsImV4cCI6MjA2NDMwMTk3MH0.LepHMvVXSwJuXLtvQHFdzhZt6Vb6bq0po1Z5laqXhbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);